In [118]:
import pandas as pd
#import time 
import datetime as dt
from datetime import date
from dateutil.relativedelta import relativedelta
import warnings; warnings.filterwarnings("ignore")
import numpy
from openpyxl.workbook import Workbook

In [119]:
#using openpyxl to read xlsx
path = ('data\source.xlsx')
xl = pd.ExcelFile(path)
xl_title = xl.sheet_names
#support for other titles?
df = xl.parse('source')

df.head(5)

,Display Name,ISIN,TagLvl 1,Ticker,Security Type,2022-05-01 00:00:00,2022-06-01 00:00:00
0,VEDLN 13 ⅞ 01/21/24 REGS,USV9667MAA00,NONCHINAASIAHYS,VEDLN,Bonds,8200.0,5000.0
1,MONMIN 9 ¼ 04/15/24 REGS,USG61759AA70,NONCHINAASIAHYS,MONMIN,Bonds,10000.0,10000.0
2,INDYIJ 8 ¼ 10/22/25 REGS,USY39690AA30,NONCHINAASIAHYS,INDYIJ,Bonds,9400.0,9400.0
3,VEDLN 6 ⅜ 07/30/22 REGS,USG9328DAM23,NONCHINAASIAHYS,VEDLN,Bonds,11600.0,11600.0
4,ANTOIL 7 ½ 12/02/22,XS2082380515,CHINAINDUSTRIAL,ANTOIL,Bonds,7700.0,7700.0

In [120]:
#expand column
df.head

today = date.today()
#this needs to support multiple date
start = df.columns[5]
end = df.columns[6]
print(type(start), type(end))
print(start, end)

<class 'datetime.datetime'> <class 'datetime.datetime'>
2022-05-01 00:00:00 2022-06-01 00:00:00

In [121]:
col_no = (end - start).days

#this is preset to column for start, as assumed positions unchanged
position_list = df.iloc[:,5]

#assuming unchanged position
#fetching the datetime into columns
for i in range(col_no):
    position = i+5
    start += dt.timedelta(days=1)
    col_name = str(start)
    df.insert(position, col_name , position_list)
    
col = df.shape[1]-5
row = df.shape[0]

In [126]:
df.head(5)
inter1 = df
inter1.head(10)

,Display Name,ISIN,TagLvl 1,Ticker,Security Type,2022-05-02 00:00:00,2022-05-03 00:00:00,2022-05-04 00:00:00,2022-05-05 00:00:00,2022-05-06 00:00:00,...,2022-05-25 00:00:00,2022-05-26 00:00:00,2022-05-27 00:00:00,2022-05-28 00:00:00,2022-05-29 00:00:00,2022-05-30 00:00:00,2022-05-31 00:00:00,2022-06-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00
0,VEDLN 13 ⅞ 01/21/24 REGS,USV9667MAA00,NONCHINAASIAHYS,VEDLN,Bonds,8200.0,8200.0,8200.0,8200.0,8200.0,...,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,5000.0
1,MONMIN 9 ¼ 04/15/24 REGS,USG61759AA70,NONCHINAASIAHYS,MONMIN,Bonds,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
2,INDYIJ 8 ¼ 10/22/25 REGS,USY39690AA30,NONCHINAASIAHYS,INDYIJ,Bonds,9400.0,9400.0,9400.0,9400.0,9400.0,...,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0
3,VEDLN 6 ⅜ 07/30/22 REGS,USG9328DAM23,NONCHINAASIAHYS,VEDLN,Bonds,11600.0,11600.0,11600.0,11600.0,11600.0,...,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0
4,ANTOIL 7 ½ 12/02/22,XS2082380515,CHINAINDUSTRIAL,ANTOIL,Bonds,7700.0,7700.0,7700.0,7700.0,7700.0,...,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0
5,EHICAR 7 ¾ 11/14/24,XS2335327388,CHINAINDUSTRIAL,EHICAR,Bonds,8200.0,8200.0,8200.0,8200.0,8200.0,...,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0
6,PEMEX 6 ½ 03/13/27,US71654QCG55,OTHEREMHYS,PEMEX,Bonds,8100.0,8100.0,8100.0,8100.0,8100.0,...,8100.0,8100.0,8100.0,8100.0,8100.0,8100.0,8100.0,8100.0,8100.0,8100.0
7,ASRIIJ 8 ¼ 11/02/25,XS2238947126,NONCHINAASIAHYS,ASRIIJ,Bonds,5650.0,5650.0,5650.0,5650.0,5650.0,...,5650.0,5650.0,5650.0,5650.0,5650.0,5650.0,5650.0,5650.0,5650.0,5650.0
8,ABMMIJ 9 ½ 08/05/26 REGS,USY708CHAB61,NONCHINAASIAHYS,ABMMIJ,Bonds,4500.0,4500.0,4500.0,4500.0,4500.0,...,4500.0,4500.0,4500.0,4500.0,4500.0,4500.0,4500.0,4500.0,4500.0,4500.0
9,STCITY 6 07/15/25 REGS,USG85381AE48,NONCHINAASIAHYS,STCITY,Bonds,6300.0,6300.0,6300.0,6300.0,6300.0,...,6300.0,6300.0,6300.0,6300.0,6300.0,6300.0,6300.0,6300.0,6300.0,6300.0

In [125]:
#calculating mkt val
#reading / creating new sheet for intermediate 2

inter2 = xl.parse('intermediate2')

inter2.head(5)

global cash_row
#bloomberg insert first settlement data
inter2.insert(5, "first settlement", position_list)

#fix this use col 4 to check the type to be cash
for i in range(df.shape[0]):
    if "cash" in df.iloc[i,0]:
        inter2.iloc[i,5] = "n/a"
        cash_row = i;
    else:
        #first settlement data obtained
        inter2.iloc[i,5] = today - dt.timedelta(days = 400)


#bloomberg insert price data (test)
inter2.iloc[:,6:] = 1
print(inter2.iloc[:,5:])

df.head(5)

   first settlement  2022-05-01 00:00:00  2022-05-02 00:00:00  \
0        2021-05-10                    1                    1
1        2021-05-10                    1                    1
2        2021-05-10                    1                    1
3        2021-05-10                    1                    1
4        2021-05-10                    1                    1
..              ...                  ...                  ...
66       2021-05-10                    1                    1
67       2021-05-10                    1                    1
68       2021-05-10                    1                    1
69       2021-05-10                    1                    1
70       2021-05-10                    1                    1

    2022-05-03 00:00:00  2022-05-04 00:00:00  2022-05-05 00:00:00  \
0                     1                    1                    1
1                     1                    1                    1
2                     1                    1                    1
3                     1                    1                    1
4                     1                    1                    1
..                  ...                  ...                  ...
66                    1                    1                    1
67                    1                    1                    1
68                    1                    1                    1
69                    1                    1                    1
70                    1                    1                    1

    2022-05-06 00:00:00  2022-05-07 00:00:00  2022-05-08 00:00:00  \
0                     1                    1                    1
1                     1                    1                    1
2                     1                    1                    1
3                     1                    1                    1
4                     1                    1                    1
..                  ...                  ...                  ...
66                    1                    1                    1
67                    1                    1                    1
68                    1                    1                    1
69                    1                    1                    1
70                    1                    1                    1

    2022-05-09 00:00:00  ...  2022-06-21 00:00:00  2022-06-22 00:00:00  \
0                     1  ...                    1                    1
1                     1  ...                    1                    1
2                     1  ...                    1                    1
3                     1  ...                    1                    1
4                     1  ...                    1                    1
..                  ...  ...                  ...                  ...
66                    1  ...                    1                    1
67                    1  ...                    1                    1
68                    1  ...                    1                    1
69                    1  ...                    1                    1
70                    1  ...                    1                    1

    2022-06-23 00:00:00  2022-06-24 00:00:00  2022-06-25 00:00:00  \
0                     1                    1                    1
1                     1                    1                    1
2                     1                    1                    1
3                     1                    1                    1
4                     1                    1                    1
..                  ...                  ...                  ...
66                    1                    1                    1
67                    1                    1                    1
68                    1                    1                    1
69                    1                    1                    1
70                    1                    1                    1

    2022-06-26 00:00:00  2022-06-27 00:00:00  2022-06-28 00:00:00  \
0                     1                    1                    1
1                     1                    1                    1
2                     1                    1                    1
3                     1                    1                    1
4                     1                    1                    1
..                  ...                  ...                  ...
66                    1                    1                    1
67                    1                    1                    1
68                    1                    1                    1
69                    1                    1                    1
70                    1                    1                    1

    2022-06-29 00:00:00  2022-06-30 00:00:00
0                     1                    1
1                     1                    1
2                     1                    1
3                     1                    1
4                     1                    1
..                  ...                  ...
66                    1                    1
67                    1                    1
68                    1                    1
69                    1                    1
70                    1                    1

[71 rows x 62 columns]

,Display Name,ISIN,TagLvl 1,Ticker,Security Type,2022-05-02 00:00:00,2022-05-03 00:00:00,2022-05-04 00:00:00,2022-05-05 00:00:00,2022-05-06 00:00:00,...,2022-05-25 00:00:00,2022-05-26 00:00:00,2022-05-27 00:00:00,2022-05-28 00:00:00,2022-05-29 00:00:00,2022-05-30 00:00:00,2022-05-31 00:00:00,2022-06-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00
0,VEDLN 13 ⅞ 01/21/24 REGS,USV9667MAA00,NONCHINAASIAHYS,VEDLN,Bonds,8200.0,8200.0,8200.0,8200.0,8200.0,...,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,8200.0,5000.0
1,MONMIN 9 ¼ 04/15/24 REGS,USG61759AA70,NONCHINAASIAHYS,MONMIN,Bonds,10000.0,10000.0,10000.0,10000.0,10000.0,...,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
2,INDYIJ 8 ¼ 10/22/25 REGS,USY39690AA30,NONCHINAASIAHYS,INDYIJ,Bonds,9400.0,9400.0,9400.0,9400.0,9400.0,...,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0,9400.0
3,VEDLN 6 ⅜ 07/30/22 REGS,USG9328DAM23,NONCHINAASIAHYS,VEDLN,Bonds,11600.0,11600.0,11600.0,11600.0,11600.0,...,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0,11600.0
4,ANTOIL 7 ½ 12/02/22,XS2082380515,CHINAINDUSTRIAL,ANTOIL,Bonds,7700.0,7700.0,7700.0,7700.0,7700.0,...,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0,7700.0

In [ ]:
#will accept inter1 row and col
def mktval(row, col, cpn):
    #cal accrued interest first
    year
    position = inter1.iloc[row,col]
    price = inter2.iloc[row,col]
    settle_date = inter2.iloc[row,col+1]
    while (settle_date < today):
        settlement += relativedelta(months=+6)

    if settlement = today :
        interest = 0
        maturity = true    
    else:
        interest = position*1000*(settlement-today).days/360 * (cpn/100)*0.5
        
    
    mkt = position*price*1000
      
    return mkt + interest

In [ ]:
#may need to fix, just copy the col from inter 1 and fill in 
global maturity = false
output1 = xl.parse('output1')


#run mktval for weekdays, cash out for maturity
#run special case detection for weekends
#account for weekend maturity, weekend coupon, weekend 
#maybe set case for monday -> account for new cf
#also deal with row of cash

for col in range(inter1.shape[1]):
    maturity = false
    #case for weekend
    if inter1.columns[row].weekday()>4:
        
    #case for weekdays
    else:
        for row in range(inter1.shape[0]):
            output1.iloc[row,col] = mktval(row,col